/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.82
 * Generated at: 2018-08-24 16:02:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.base;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class newSpeed_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<title>Insert title here</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(document).ready(function newspeed() {\r\n");
      out.write("\t\t\t$.ajax({  \r\n");
      out.write("\t\t\t    type : \"POST\",  \r\n");
      out.write("\t\t\t    url : \"/newSpeedAjax.do\",  \r\n");
      out.write("\t\t\t    dataType : \"JSON\",\r\n");
      out.write("\t\t\t    success : function(data){  \r\n");
      out.write("\t\t\t    \tvar list = data[\"newList\"];\r\n");
      out.write("\t                var html = \"<table class='table table-hover;' style='background: #EAEAEA;'>\";\r\n");
      out.write("\t                for(var i=0; i<list.length; i++){\r\n");
      out.write("\t                    html += '<tr>';\r\n");
      out.write("\t                    html += '<td onclick=\"javascript:dddd()\">'+ '<strong>' + list[i].sendNme + '</strong>' + '님이&nbsp;' + '<strong>'  + list[i].nmeCardLastNme + list[i].nmeCardFirstNme + '</strong>';\r\n");
      out.write("\t                    if(list[i].newspeedType=='Y'){\r\n");
      out.write("\t                    \thtml+= '&nbsp;명함을' + '<br>'+ '공유했습니다.' + '<br>';\r\n");
      out.write("\t                    }\r\n");
      out.write("\t                    else if(list[i].newspeedType=='N'){\r\n");
      out.write("\t                    \thtml+= '&nbsp;명함을' + '<br>'+ '공유해제했습니다.' + '<br>';\r\n");
      out.write("\t                    }\r\n");
      out.write("\t                    else if(list[i].newspeedType=='C'){\r\n");
      out.write("\t                    \thtml+= '&nbsp;명함의' + '<br>'+ '커뮤니케이션을 보냈습니다.' + '<br>';\r\n");
      out.write("\t                    }\r\n");
      out.write("\t                    else if(list[i].newspeedType=='CC'){\r\n");
      out.write("\t                    \thtml+= '&nbsp;명함의' + '<br>'+ '커뮤니케이션을 등록했습니다.' + '<br>';\r\n");
      out.write("\t                    }\r\n");
      out.write("\t                    else if(list[i].newspeedType=='CU'){\r\n");
      out.write("\t                    \thtml+= '&nbsp;명함의' + '<br>'+ '커뮤니케이션을 수정했습니다.' + '<br>';\r\n");
      out.write("\t                    }\r\n");
      out.write("\t                    else if(list[i].newspeedType=='CD'){\r\n");
      out.write("\t                    \thtml+= '&nbsp;명함의' + '<br>'+ '커뮤니케이션을 삭제했습니다.' + '<br>';\r\n");
      out.write("\t                    }\r\n");
      out.write("\t                    html += '</td>';\r\n");
      out.write("\t                    html += '</tr>';\r\n");
      out.write("\t                };\r\n");
      out.write("\t                html += '</table>';\r\n");
      out.write("\t                $(\"#newspeedSelect\").html(html);\r\n");
      out.write("\t            },\r\n");
      out.write("\t\t\t    error:function(xhr,status,error){ //ajax 오류인경우  \r\n");
      out.write("\t\t\t    \talert(\"$\");\r\n");
      out.write("\t\t            alert(\"error\\nxhr : \" + xhr + \", status : \" + status + \", error : \" + error);             \r\n");
      out.write("\t\t   \t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\t\t\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div style=\"width:300px;\">\r\n");
      out.write("\t\t<div style=\"width:200px;\">\r\n");
      out.write("\t\t\t<div style=\"width:100%;\" align=\"center\">\r\n");
      out.write("\t\t\t\t<div style=\"display:inline\">\r\n");
      out.write("\t\t\t\t\t<h3>최신정보\r\n");
      out.write("\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div style=\"width:200px; height:570px; overflow-y:auto;\" id=\"newspeedSelect\"  class=\"content; table-responsive\" data-mcs-theme=\"dark\">\r\n");
      out.write("   \t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
